import "./globals.css";
import { Lexend } from 'next/font/google';
import { Toaster } from "react-hot-toast";
import Providers from "./providers";
import Header from "./components/Header";
import HandleFooter from "./components/HandleFooter";



const lexend = Lexend({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700', '900'],
  variable: '--font-lexend',
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {  
 

  return (
      <html lang="en">
        <body className={`${lexend.variable} font-display min-h-screen flex flex-col`}>
          <Providers>
            <Header />
            
            {/* Main content grows to fill space */}
            <main className="flex-1">
              {children}
            </main>

            <HandleFooter /> {/* Footer will stay at bottom */}
          </Providers>

          <Toaster position="top-right" reverseOrder={false} />
        </body>
      </html>

  );
}
